<?php
/**
 * Loads plugin functionality.
 *
 * @package MJ/PostSeries
 */

namespace MJ\PostSeries;

defined( 'ABSPATH' ) || exit;

use MJ\PostSeries\Registry\Container;
use MJ\PostSeries\TaxonomyController;
use MJ\PostSeries\PostContent;
use MJ\PostSeries\BlockTypes\PostSeries;

/**
 * Takes care of bootstrapping the plugin.
 */
class Plugin {
	/**
	 * Main __FILE__ reference.
	 *
	 * @var string
	 */
	private $file = '';

	/**
	 * Holds the Dependency Injection Container
	 *
	 * @var Container
	 */
	private $container;

	/**
	 * Constructor.
	 *
	 * @param Container $container  The Dependency Injection Container.
	 * @param string    $file Main plugin __FILE__ reference.
	 */
	public function __construct( Container $container, $file ) {
		$this->file      = $file;
		$this->container = $container;
		$this->init();
	}

	/**
	 * Initialize class features.
	 */
	private function init() {
		add_action( 'init', array( $this, 'load_plugin_textdomain' ) );
		add_action( 'init', array( $this, 'register_assets' ) );
		add_action( 'init', array( $this, 'register_block_types' ) );
		add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_scripts' ) );

		$this->container->register(
			TaxonomyController::class,
			function () {
				return new TaxonomyController();
			}
		);
		$this->container->register(
			Template::class,
			function () {
				$default_template_dir = dirname( $this->file ) . '/templates/';
				return new Template( $default_template_dir );
			}
		);
		$this->container->register(
			PostContent::class,
			function ( Container $container ) {
				return new PostContent( $container->get( Template::class ) );
			}
		);
		$this->container->register(
			PostSeries::class,
			function ( Container $container ) {
				return new PostSeries( $container->get( PostContent::class ), dirname( $this->file ) . '/build/post-series-block' );
			}
		);

		$this->container->get( TaxonomyController::class );
		$this->container->get( PostContent::class );
	}

	/**
	 * Init localizations.
	 */
	public function load_plugin_textdomain() {
		load_plugin_textdomain( 'wp-post-series', false, dirname( plugin_basename( $this->file ) ) . '/languages/' );
	}

	/**
	 * Register the frontend script and style. These are shared by the block (via block.json) and the automatically
	 * inserted series box.
	 */
	public function register_assets() {
		$build_dir  = dirname( $this->file ) . '/build/';
		$style_path = $build_dir . 'post-series.css';

		// Stylesheet-only entries don't get an asset file, so version by modification time.
		wp_register_style( 'wp-post-series', plugins_url( 'build/post-series.css', $this->file ), array(), file_exists( $style_path ) ? (string) filemtime( $style_path ) : false );
		wp_style_add_data( 'wp-post-series', 'rtl', 'replace' );

		$script_asset = $this->get_asset( $build_dir . 'frontend.asset.php' );

		wp_register_script( 'wp-post-series', plugins_url( 'build/frontend.js', $this->file ), $script_asset['dependencies'], $script_asset['version'], true );
	}

	/**
	 * Register block types.
	 */
	public function register_block_types() {
		$this->container->get( PostSeries::class )->register_block_type();
	}

	/**
	 * Enqueue scripts and styles.
	 */
	public function enqueue_scripts() {
		wp_enqueue_style( 'wp-post-series' );
	}

	/**
	 * Read a build asset file generated by @wordpress/scripts.
	 *
	 * @param string $asset_path Path to asset file.
	 * @return array{dependencies: string[], version: string|false}
	 */
	protected function get_asset( $asset_path ) {
		$asset = is_readable( $asset_path ) ? require $asset_path : array();

		return array(
			'dependencies' => isset( $asset['dependencies'] ) ? $asset['dependencies'] : array(),
			'version'      => isset( $asset['version'] ) ? $asset['version'] : false,
		);
	}
}
