name: CI
on:
    pull_request:
    push:
        branches:
            - trunk
permissions:
    contents: read
jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version-file: .nvmrc
                  cache: npm
            - run: composer install --no-interaction
            - run: npm ci
            - run: npm run lint

    test:
        name: PHPUnit and E2E
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version-file: .nvmrc
                  cache: npm
            - run: composer install --no-interaction
            - run: npm ci
            - run: npm run build
            - run: npm run wp-env start
            - run: npm run test:php
            - run: npx playwright install --with-deps chromium
            - run: npm run test:e2e
            - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
              if: failure()
              with:
                  name: e2e-artifacts
                  path: artifacts
                  if-no-files-found: ignore
